# Site Settings
baseurl: 		""
title: 			Parker - Web Architect

name: 			Welcome <i>to</i> Parker
description: 	Web Architect and Designer 
url: 			"http://www.parkerrr.com"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		thnkco
email: 			jason@parkerrr.com

disqus: 		yetle99
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Jason Beaton.	

# Build Settings
permalinks: 	pretty
